### ISSUE TITLE
Improve efficiency of the navigator

### ISSUE THREAD

**Issue by illustifa** [grimur82/SE459#4]
Instead of the sweeper randomly picking the next cell to go to.

**Comment by grimur82** [comment]
The sweeper goes from where it has gone in visited data structure and not
randomly anymore. I don´t understand what your asking for. Our floorplan
doesn't have any weight, each cell is the same ? I could try to do a A*
algorithm, if that's what your asking for ?

Grimur

**Comment by illustifa** [comment]
Right now the sweeper randomly selects one of four positions to go to, given that it isn't an obstacle. Say that the TOP cell is dirty (in unvisited map), but LEFT, RIGHT, and BOTTOM are clean (in visited map). The idea is that the sweeper would select the TOP cell instead of the others so that it is more efficient and saves time and power. We don't want the sweeper potentially going around in circles in an area that's already clean.

If all of the surrounding cells are clean/visited, then it would fire some kind of algorithm to check against both hashmaps and find the nearest dirty cell.

**Comment by illustifa** [comment]
By the way I'm not actually asking you to do this since I already said I would do it. I added a "TODO" label, just as a personal reminder.

Edit: Oh duh...that's what the assigned feature is for.

**Comment by grimur82** [comment]
Tiffany lets get together. It does make sense, but I think it will be
handled  faster if we get together. Also,  the professor mentioned there
will be a presentation in class for our project next week. He will post the
structure on that soon. Lets discuss that too.

**Comment by illustifa** [comment]
I'm actually almost done with it.

But I can meet up to discuss the presentation. I'll email you and everyone.

**Comment by grimur82** [comment]
Ok sounds good.

Grimur

**Comment by illustifa** [comment]
c3193b06c4a8653f61c117db5d0b41c928665e89
